### ISSUE TITLE
User can select a color

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/vue-colors#3]
# Motivation
We want to be able to see a color picker and pick a color.

# Tasks
- [x] Get a color picker library.
- [x] Be able to render it on the page.
- [x] Be able to register events when the user selects a color.
- [x] Be able to see slider changes when selecting a hex.
- [x] Be able to see a hex change when selecting a slider value.
- [x] Be able to see the text changes for the selected hex when you use the color select or the sliders.
