### ISSUE TITLE
User can save a color

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/vue-colors#5]
# Motivation
We want to demonstrate communicating with a rest API and show how to communicate with other components in an application. Also, this example should be a good one on how to render a list as well as adding to one.

# Tasks
- [x] Create a postgres database to save colors.
- [x] Create a submit event the emits a color event.
- [x] Create another component that gets a list of all your colors.
- [x] If there are no initial colors saved, create a conditional render that says "You don't have any saved colors".
- [x] Be able to add a color to the database.
- [x] Be able to add the color to the list after a successful database entry.
