### ISSUE TITLE
Write up Unit Tests and README

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/vue-colors#7]
# Motivation
Now that we have created a basic app, we want to write a README and write some unit tests. 

# Tasks
- [x] Write up the README.
- [x] Write some basic unit tests.
- [x] Be able to have all the tests pass.
- [x] Populate the README with some pictures.

![colors](https://user-images.githubusercontent.com/26865352/61611309-52326780-ac10-11e9-94dd-d4959eddf9a6.gif)
